pipeline {
    agent any

    tools {
        maven 'Maven3'
    }

    environment {
        PATH = "C:\\Program Files\\Docker\\Docker\\resources\\bin;${env.PATH}"
        JAVA_HOME = 'C:\\Program Files\\Java\\jdk-21'
        SONARQUBE_SERVER = 'SonarQubeServer'
        SONAR_TOKEN = 'sqa_fd7d68d681ef29d068fa007c76633a0181076fa1'
        DOCKERHUB_CREDENTIALS_ID = 'Docker_Hub'
        DOCKERHUB_REPO = 'joniheikk/assignment_5'
        DOCKER_IMAGE_TAG = 'latest'
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'master', url: 'https://github.com/Jonijermu/otp2_assignments.git'
            }
        }

       stage('Build') {
           steps {
               // Build only assignment_5 module
               dir('assignment_5') {
                   bat 'mvn clean install'
               }
           }
       }

       stage('SonarQube Analysis') {
           steps {
               dir('assignment_5') {
                   script {
                       def scannerHome = tool 'SonarScanner'
                       withSonarQubeEnv('SonarQubeServer') {
                           bat """
                               "${scannerHome}\\bin\\sonar-scanner" ^
                               -Dsonar.projectKey=assignment_5 ^
                               -Dsonar.projectName=assignment_5 ^
                               -Dsonar.sources=src ^
                               -Dsonar.java.binaries=target/classes ^
                               -Dsonar.host.url=http://localhost:9000 ^
                               -Dsonar.login=${env.SONAR_TOKEN}
                           """
                       }
                   }
               }
           }
       }

        stage('Build Docker Image') {
            steps {
                dir('assignment_5') {
                    script {
                        docker.build("${DOCKERHUB_REPO}:${DOCKER_IMAGE_TAG}")
                    }
                }
            }
        }

         stage('Push Docker Image to Docker Hub') {
            steps {
                dir('assignment_5') {
                    script {
                        docker.withRegistry('https://index.docker.io/v1/', DOCKERHUB_CREDENTIALS_ID) {
                            docker.image("${DOCKERHUB_REPO}:${DOCKER_IMAGE_TAG}").push()
                        }
                    }
                }
            }
        }
    }
}
